layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  facebook: vtrnnhlinh
  hackerrank: vtrnnhlinh
  # instagram: your_username
  # keybase: your_username
  linkedin: vtrnnhlinh
  # mastodon: your_username
  # medium: your_username
  stackoverflow: 8149495
  # telegram: your_username
  twitter: vtrnnhlinh
  # unsplash: your_username
  # vk: your_username
  website: https://vtrnnhlinh.github.io
  # youtube: your_username

topics:
  - name: Computer Science

  - name: Mathematics

  - name: Social Sciences
  
  - name: Natural Sciences